### ISSUE TITLE
running error about main.py

### ISSUE THREAD

**Issue by Airotong** [lvapeab/ABiViRNet#2]
Dear Author,

It occurred a problem "KeyError : 'references' " in code "gts = extra_vars[split]['references']" in file evaluation.py when I ran main.py. After a long time for training, the programme stooped here. 

I would like to know why this problem occurred and how can I fix it? On the other hand, how could I skip training stage directly run evaluation stage? Because every time I  modify the code, I need to run main.py and waiting for training, although the training is correct.

I am new to this area, and looking forward to your apply.

Thank you!

**Comment by lvapeab** [comment]
Solved by e-mail. There was a minor problem in the `captions.id.en` file. I'm closing this.
