### ISSUE TITLE
wish to make some changes: different output & no pre-determined images features

### ISSUE THREAD

**Issue by ron-weiner** [lvapeab/ABiViRNet#3]
Hey!
Great work, thank you so much for sharing the code.

I have a huge dataset of videos with a grade between 0 to 1 for each video.
This main thing is that there aren't annotated features on the frames.
I wish to alter your code in a way that i can predict the grade of a given video.

i think that a single grade can be treated as two classes of good&bad, or something such as this.

what do you think? can you focus me and aiming me on how to implement it using your code?

thanks a lot in advance!

**Comment by lvapeab** [comment]
Hi @ron-weiner ,

thanks for your interest in the project. 

You definitely can use it for your problem. Instead a sequence predictor, you need a (binary) classifier. Therefore, you can remove the decoder RNN and substitute it by a classifier (e.g. Dense layers). We have some projects that use this approach. Please, take a look at:

- [sentence-selectioNN](https://github.com/lvapeab/sentence-selectioNN): This project classifies text into "in-domain" or "out-of-domain" (as yours, a binary classification problem). It computes a representation of the text using RNNs or CNNs and applies Dense layers afterwards.

- [VIBIKNet](https://github.com/MarcBS/VIBIKNet): This tackles the visual question answering problem. It encodes an image and a question, merges them and predicts the answer as a classification problem.

Cheers!

PS: Those repositories may contain deprecated code w.r.t. the current version of Keras, but I think you can take the main flavour of the changes required for your problem ;)

**Comment by ron-weiner** [comment]
Thanks for the quick reply!
I want to rewrite it for python 3, it will we more handy for the future.
Can you focus me on what i should dismiss if i don't want to use any features on the frames?

Do you think that this project is the up to date in that field? do you have/know additional projects in that level which might be good to start with?

Thank you!!

Cheers
