### ISSUE TITLE
For Single video as an input

### ISSUE THREAD

**Issue by vinaysworld** [lvapeab/ABiViRNet#4]
hi
After training, how we have to give input as single video and generate output, where we can store result

**Comment by lvapeab** [comment]
Hi,

you should modify [these lines](https://github.com/lvapeab/ABiViRNet/blob/master/config.py#L186-L189) in `config.py`and run `main.py`. Then, you'll sample and evaluate on the sets specified in the `EVAL_ON_SETS` parameter.

**Comment by vinaysworld** [comment]
but what modification should done, can you give me demo of any video

**Comment by lvapeab** [comment]
This is addressed with the `caption.py` from [interactive-keras-captioning](https://github.com/lvapeab/interactive-keras-captioning#decoding). I'm closing this.
